### ISSUE TITLE
Error with Monday

### ISSUE THREAD

**Issue by deyko** [bradymholt/cRonstrue#108]
Hello Brady! Thank you very much for this library, it has been very helpful!

When I've been using it, I've realized what could be a mistake.

If you create a cron for the day Wednesday, Tuesday or Sunday, there is no problem, the library returns the correct message, however, if you create it for Monday (1/1) it does not show the message.

I leave the generated example:

> 0 52 13? * 3/1 * -> At 01:52 PM, every 1 day of the week, Wednesday through Saturday
> 0 52 13? * 2/1 * -> At 01:52 PM, every 1 day of the week, Tuesday through Saturday
> **0 52 13? * 1/1 * -> At 01:52 PM**
> 0 52 13? * 0/1 * -> At 01:52 PM, every 1 day of the week, Sunday through Saturday

**Comment by bradymholt** [comment]
Glad you like the library!

The format of those expressions looks off and I don't get the same output.

If I use `0 52 13 ? * 3/1`, then I get "At 01:52 PM, Wednesday through Saturday" for example.  A recent change removed the "every 1 day of the week" verbiage in these cases.  Also, for the `0 52 13 ? * 3/1`, the absence of "every day" at the end is intentional.  It's implied that it will run every day at 01:52PM.

You can use the `verbose` option for different output:

```
construe.toString("0 52 13 ? * 3/1", {verbose:true}) // At 01:52 PM, every day, Wednesday through Saturday
construe.toString("0 52 13 ? * 1/1", {verbose:true}) // At 01:52 PM, every day
```
