### ISSUE TITLE
German translation for day-of-week repetition is misleading

### ISSUE THREAD

**Issue by FelixZett** [bradymholt/cRonstrue#65]
I decided to open an issue to be able to track the problem discussed in f3da9d15d2656dc2ed221caa0654beecc7d13dca better.
As I said I looked into the translation and I think I am not in the position to find a good solution.
For now (and in my Use-Case) it would be preferable to revert the changes from #63, but as discussed by @seveves in #60 this is not the ultimate solution.

This may be a bit tricky in german overall, so I will give an example for the problem.
The cron-expression `0 0 12 ? * SUN *` will read
>Täglich um 12:00, nur am Sonntag

which translates to
>Daily, at 12:00 PM, only on Sunday

Without localisation I get
>At 12:00 PM, only on Sunday

which would in turn translate back to
>Um 12:00, nur am Sonntag

which was the output before #60.
Of course, technically it is still correct, but as users may stop reading early, having the "Daily" up front would lead to misleading information

I do not know @seveves Use-Case but in my Use-Case this is not acceptable. I understand that "Um 12:00" ("At 12:00 PM") does not give any information on the daily repetition, but it is IMHO much preferable to the disaster in my example.

I think a better solution would be to put the daily-info after the time. Something like "At 12:00 PM, every Day" would be much preferable to "At 12:00 PM" but I know there are limitations on what info is to be displayed so we don't end up with "At 12:00 PM, every Day, every Month, any Year"

What is your opinion on the matter? I did not want to propose any changes until I know in which direction the libraries translation should be taken.

**Comment by bradymholt** [comment]
Thanks for the writeup!  Let's revert https://github.com/bradymholt/cRonstrue/commit/f3da9d15d2656dc2ed221caa0654beecc7d13dca for now since what explain makes a lot of sense.  I'd prefer to keep any changes simple and avoid a major redesign to accomodate this.  One simple option may to introduce another [i18n method](https://github.com/bradymholt/cRonstrue/blob/master/src/i18n/locales/en.ts) that will be used _if defined_ (or not null/blank) and otherwise will be ignored.  This pattern is already being used in a limited way for some of the translations.
