### ISSUE TITLE
Set timezone

### ISSUE THREAD

**Issue by joeyJsonar** [bradymholt/cRonstrue#94]
We need a way to specify the timezone.

**Comment by bradymholt** [comment]
This is outside the scope of my intentions for this library.

**Comment by lostpebble** [comment]
That's a pity. This is a great library - but with no way to set a timezone as a reference for the language output, its not that feasible (users often need to set cron jobs according to certain country's timezone to run processing while the servers are less busy, for instance).

**Comment by bradymholt** [comment]
Are there any other libraries that do something similar? I am not aware of any.  If you need to adjust the time per a timezone, I would suggest parsing the cron, adjusting the second / minute / hour part and _then_ feeding it into cRonstrue.

**Comment by lostpebble** [comment]
I'm using your library in conjunction with https://www.npmjs.com/package/cron-parser / https://github.com/harrisiirak/cron-parser. Which you can see under options allows passing a `tz` variable in the form of `"Africa/Johannesburg"` ([tz database names](https://en.wikipedia.org/wiki/List_of_tz_database_time_zones)) etc.

> If you need to adjust the time per a timezone, I would suggest parsing the cron, adjusting the second / minute / hour part per the target timezone and _then_ feeding it into cRonstrue.

This is a very roundabout way of doing things. Adjusting the crontab programatically would require writing a lot of code or bringing in yet another library potentially.

Your library outputs language specifically based on a specific timezone perspective and a crontab. Unfortunately it always assumes our perspective is the current JavaScript execution's timezone - this is not always the case, especially because a client's timezone rarely syncs up with servers, which will mostly have their timezones set to GMT.

For example picture someone setting a crontab in France in their browser (which uses their client timezone) - this library tells them `0 0 1/24 * * *` -> `Every 24 hours, starting at 01:00 AM`, they save the crontab. Now on the server, which runs in GMT timezone, this crontab is interpreted to run - but because of the timezone it sets it to run at `01:00AM GMT` - which is in actual fact `02:00AM` in France.

**Comment by Siderite** [comment]
For me, dates on the server are all in UTC, so if someone uses a CRON syntax that specifies the exact time, there is a difference from the dates displayed on the client (which shows them in local time) and the cron that I want to display on the client as well. It would be a good feature in your library to take that into account, but I understand why you wouldn't want to go there.

**Comment by ndrsllwngr** [comment]
I'd have to agree with @Siderite there. We do have a similar setup and have to display UTC in our frontend.

**Comment by bradymholt** [comment]
PR welcome.  A step to read option (similar to dayOfWeekStartIndexZero) and adjust hour based on timezone in https://github.com/bradymholt/cRonstrue/blob/master/src/cronParser.ts might be easy to implement.

**Comment by Trial-In-Error** [comment]
Agree that option discussed by @Siderite and @ndrsllwngr would be ideal, but a useful half-way for me would be for an option that simply places or doesn't place a consumer-provided timezone label when appropriate. For instance, a cron tab of "0 * * * *" ("Every hour") does not need a timezone label, whereas a cron tab of "0 7 * * *" ("At 7:00 AM") would benefit from a timezone label.

In this world, the consumer would call cronstrue perhaps like this: `cron("0 7 * * *", { includeTZName: "UTC" })`. The library wouldn't do any translation of the cron expression to shift it from one TZ to another - it would simply label what timezone the expression is in reference to when it would be applicable.

For right now, I'm parsing the incoming cron, and, in cases where the hour is specified, am appending ", UTC" (or localized equivalent), but it would be nice for cronstrue to "own" this behavior.

**Comment by jasondarnell** [comment]
+1 for timezone. I would also like to show UTC as local time.

**Comment by bradymholt** [comment]
I'm going to close this out because I am not planning on implementing this feature.  As [mentioned above](https://github.com/bradymholt/cRonstrue/issues/94#issuecomment-584289005), I would welcome a PR that does the timezone adjustment.

**Comment by bradymholt** [comment]
Implemented here: https://github.com/bradymholt/cRonstrue/pull/288
